import type { GuidePage } from "../types";

export const ADMIN_PAGES: GuidePage[] = [
  {
    id: "admin_overview",
    match: ["/admin", "/admin/dashboard"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_overview.title" },
      { target: "stats:filters", text: "tours.common.statsFilters" },
      { target: "overview:kpis", text: "tours.admin_overview.kpis" },
      { target: "overview:charts", text: "tours.admin_overview.charts" },
      { target: "overview:modules", text: "tours.admin_overview.modules" },
    ],
    suggestions: ["suggest.staff.revenueMonth", "suggest.staff.metricsRegion"],
  },
  {
    id: "admin_ceo",
    match: ["/admin/ceo"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_ceo.title" },
      { target: "stats:filters", text: "tours.common.statsFilters" },
      { target: "ceo:kpis", text: "tours.admin_ceo.kpis" },
      { target: "ceo:revenue-trend", text: "tours.admin_ceo.trend" },
      { target: "ceo:funnel", text: "tours.admin_ceo.funnel" },
      { target: "ceo:channels", text: "tours.admin_ceo.channels" },
      { target: "ceo:kpi-system", text: "tours.admin_ceo.kpiSystem" },
    ],
    suggestions: ["suggest.staff.ltvCac", "suggest.staff.bestChannel"],
  },
  {
    id: "admin_pipeline",
    match: ["/admin/pipeline", "/admin/leads"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_pipeline.title" },
      { target: "pipeline:kpis", text: "tours.admin_pipeline.kpis" },
      { target: "button:new-lead", text: "tours.admin_pipeline.newLead" },
      { target: "button:auto-assign", text: "tours.admin_pipeline.autoAssign" },
      { target: "leads:filters", text: "tours.admin_pipeline.filters" },
      { target: "pipeline:board", text: "tours.admin_pipeline.board" },
    ],
    suggestions: ["suggest.staff.leadMove", "suggest.staff.leadAssign"],
  },
  {
    id: "admin_call_center",
    match: ["/admin/call-center"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_call_center.title" },
      { target: "callcenter:queue", text: "tours.admin_call_center.queue" },
      { target: "callcenter:urgent", text: "tours.admin_call_center.urgent" },
      { target: "callcenter:complaints", text: "tours.admin_call_center.complaints" },
      { target: "callcenter:board", text: "tours.admin_call_center.board" },
      { target: "callcenter:client-search", text: "tours.admin_call_center.clientSearch" },
    ],
    suggestions: ["suggest.staff.urgent", "suggest.staff.clientFind", "suggest.staff.callLog"],
  },
  {
    id: "admin_meetings",
    match: ["/admin/meetings"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_meetings.title" },
      { target: "meetings:create", text: "tours.admin_meetings.create" },
      { target: "seller:meeting-list", text: "tours.admin_meetings.list" },
    ],
    suggestions: ["suggest.staff.meetingStart"],
  },
  {
    id: "admin_call_analytics",
    match: ["/admin/call-analytics"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_call_analytics.title" },
      { target: "stats:filters", text: "tours.common.statsFilters" },
      { target: "call-analytics:kpis", text: "tours.admin_call_analytics.kpis" },
      { target: "call-analytics:by-day", text: "tours.admin_call_analytics.byDay" },
      { target: "call-analytics:agents", text: "tours.admin_call_analytics.agents" },
    ],
    suggestions: ["suggest.staff.missedCalls", "suggest.staff.topOperator"],
  },
  {
    id: "admin_retention",
    match: ["/admin/retention"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_retention.title" },
      { target: "stats:filters", text: "tours.common.statsFilters" },
      { target: "retention:kpis", text: "tours.admin_retention.kpis" },
      { target: "retention:at-risk", text: "tours.admin_retention.atRisk" },
      { target: "retention:at-risk-client", text: "tours.admin_retention.winBack" },
      { target: "retention:upsell", text: "tours.admin_retention.upsell" },
    ],
    suggestions: ["suggest.staff.atRiskClients", "suggest.staff.winBackClient"],
  },
  {
    id: "admin_b2b",
    match: ["/admin/b2b"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_b2b.title" },
      { target: "button:new-b2b-client", text: "tours.admin_b2b.add" },
      { target: "b2b:list", text: "tours.admin_b2b.list" },
      { target: "b2b:documents", text: "tours.admin_b2b.documents" },
      { target: "b2b:stage", text: "tours.admin_b2b.stage" },
    ],
    suggestions: ["suggest.staff.b2bInvoice", "suggest.staff.b2bAdd"],
  },
  {
    id: "admin_marketplace",
    match: ["/admin/marketplace"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_marketplace.title" },
      { target: "marketplace:tabs", text: "tours.admin_marketplace.tabs" },
      { target: "marketplace:period", text: "tours.admin_marketplace.period" },
      { target: "marketplace:filters", text: "tours.admin_marketplace.filters" },
      { target: "marketplace:kpis", text: "tours.admin_marketplace.kpis" },
      { target: "marketplace:orders-list", text: "tours.admin_marketplace.orders" },
    ],
    suggestions: ["suggest.staff.ordersPaidToday", "suggest.staff.sellerOrders"],
  },
  {
    id: "admin_services",
    match: ["/admin/services"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_services.title" },
      { target: "services:categories", text: "tours.admin_services.categories" },
      { target: "button:new-service", text: "tours.admin_services.add" },
      { target: "services:filters", text: "tours.admin_services.filters" },
      { target: "services:list", text: "tours.admin_services.list" },
    ],
    suggestions: ["suggest.staff.servicePrice", "suggest.staff.serviceAdd"],
  },
  {
    id: "admin_plans",
    match: ["/admin/plans"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_plans.title" },
      { target: "button:new-plan", text: "tours.admin_plans.add" },
      { target: "plans:filters", text: "tours.admin_plans.filters" },
      { target: "plans:list", text: "tours.admin_plans.list" },
      { target: "plans:item-actions", text: "tours.admin_plans.actions" },
    ],
    suggestions: ["suggest.staff.planPrice", "suggest.staff.planOff"],
  },
  {
    id: "admin_templates",
    match: ["/admin/templates"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_templates.title" },
      { target: "button:new-template", text: "tours.admin_templates.add" },
      { target: "button:import-templates", text: "tours.admin_templates.import" },
      { target: "templates:search", text: "tours.admin_templates.search" },
      { target: "templates:list", text: "tours.admin_templates.list" },
    ],
    suggestions: ["suggest.staff.templateImport", "suggest.staff.templateEdit"],
  },
  {
    id: "admin_ads",
    match: ["/admin/ads"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_ads.title" },
      { target: "button:new-ad", text: "tours.admin_ads.add" },
      { target: "ads:list", text: "tours.admin_ads.list" },
    ],
    suggestions: ["suggest.staff.adAdd", "suggest.staff.adStop"],
  },
  {
    id: "admin_register_requests",
    match: ["/admin/register-requests"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_register_requests.title" },
      { target: "register-requests:stats", text: "tours.admin_register_requests.stats" },
      { target: "register-requests:role-tabs", text: "tours.admin_register_requests.roleTabs" },
      { target: "register-requests:list", text: "tours.admin_register_requests.list" },
      { target: "button:register-request-detail", text: "tours.admin_register_requests.detail" },
      { target: "register-requests:decision", text: "tours.admin_register_requests.decision" },
    ],
    suggestions: ["suggest.staff.sellerApprove", "suggest.staff.sellerDocs"],
  },
  {
    id: "admin_reviews",
    match: ["/admin/reviews"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_reviews.title" },
      { target: "reviews:seller-tabs", text: "tours.admin_reviews.tabs" },
      { target: "reviews:list", text: "tours.admin_reviews.list" },
      { target: "reviews:moderation", text: "tours.admin_reviews.moderation" },
    ],
    suggestions: ["suggest.staff.reviewApprove", "suggest.staff.reviewRemove"],
  },
  {
    id: "admin_payouts",
    match: ["/admin/payouts"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_payouts.title" },
      { target: "payouts:reconciliation", text: "tours.admin_payouts.reconciliation" },
      { target: "payouts:list", text: "tours.admin_payouts.list" },
      { target: "payouts:item-actions", text: "tours.admin_payouts.markPaid" },
    ],
    suggestions: ["suggest.staff.payoutMark", "suggest.staff.platformFee"],
  },
  {
    id: "admin_approvals",
    match: ["/admin/approvals"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_approvals.title" },
      { target: "approvals:queue", text: "tours.admin_approvals.queue" },
      { target: "approvals:actions", text: "tours.admin_approvals.actions" },
    ],
    suggestions: ["suggest.staff.refundApprove"],
  },
  {
    id: "admin_legal_aid",
    match: ["/admin/legal-aid"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_legal_aid.title" },
      { target: "legal-aid:list", text: "tours.admin_legal_aid.list" },
      { target: "button:legal-aid-detail", text: "tours.admin_legal_aid.detail" },
    ],
    suggestions: ["suggest.staff.legalAidNew"],
  },
  {
    id: "admin_notifications",
    match: ["/admin/notifications"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_notifications.title" },
      { target: "notifications:mode", text: "tours.admin_notifications.mode" },
      { target: "notifications:recipients", text: "tours.admin_notifications.recipients" },
      { target: "notifications:compose", text: "tours.admin_notifications.compose" },
      { target: "button:send-notification", text: "tours.admin_notifications.send" },
    ],
    suggestions: ["suggest.staff.notifyRole", "suggest.staff.notifyUser"],
  },
  {
    id: "admin_integrations",
    match: ["/admin/integrations"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_integrations.title" },
      { target: "integrations:residency", text: "tours.admin_integrations.residency" },
      { target: "integrations:services", text: "tours.admin_integrations.services" },
    ],
    suggestions: ["suggest.staff.smsStatus"],
  },
  {
    id: "admin_test_otps",
    match: ["/admin/test-otps"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_test_otps.title" },
      { target: "test-otps:list", text: "tours.admin_test_otps.list" },
    ],
    suggestions: ["suggest.staff.otpCode"],
  },
  {
    id: "admin_roles",
    match: ["/admin/roles"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_roles.title" },
      { target: "button:new-role", text: "tours.admin_roles.add" },
      { target: "roles:list", text: "tours.admin_roles.list" },
      { target: "roles:assign", text: "tours.admin_roles.assign" },
      { target: "roles:matrix", text: "tours.admin_roles.matrix" },
    ],
    suggestions: ["suggest.staff.roleGive", "suggest.staff.roleCreate"],
  },
  {
    id: "admin_audit_trail",
    match: ["/admin/audit-trail"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_audit_trail.title" },
      { target: "audit:anomalies", text: "tours.admin_audit_trail.anomalies" },
      { target: "button:export-audit", text: "tours.admin_audit_trail.export" },
      { target: "audit:filters", text: "tours.admin_audit_trail.filters" },
      { target: "audit:list", text: "tours.admin_audit_trail.list" },
    ],
    suggestions: ["suggest.staff.auditUser", "suggest.staff.auditExport"],
  },
  {
    id: "admin_legal",
    match: ["/admin/legal"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_legal.title" },
      { target: "legal:tabs", text: "tours.admin_legal.tabs" },
      { target: "button:new-legal-doc", text: "tours.admin_legal.add" },
      { target: "legal:docs-list", text: "tours.admin_legal.docs" },
      { target: "legal:journal", text: "tours.admin_legal.journal" },
    ],
    suggestions: ["suggest.staff.termsVersion", "suggest.staff.consentCheck"],
  },
  {
    id: "admin_policies",
    match: ["/admin/policies"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_policies.title" },
      { target: "policies:readiness", text: "tours.admin_policies.readiness" },
      { target: "policies:sections", text: "tours.admin_policies.sections" },
      { target: "policies:unverified", text: "tours.admin_policies.unverified" },
      { target: "policies:business-hours", text: "tours.admin_policies.hours" },
    ],
    suggestions: ["suggest.staff.policyChange", "suggest.staff.holidayAdd"],
  },
  {
    id: "admin_bootstrap",
    match: ["/admin/bootstrap"],
    roles: ["staff"],
    tour: [
      { target: "ai-help:current-page", text: "tours.admin_bootstrap.title" },
      { target: "bootstrap:form", text: "tours.admin_bootstrap.form" },
    ],
  },
];
