import type { GuidePage } from "../types";

export const CLIENT_PAGES: GuidePage[] = [
  {
    id: "client_dashboard",
    match: ["/portal/client"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_dashboard.title" },
      { target: "dashboard:describe", text: "tours.client_dashboard.describe" },
      { target: "dashboard:urgent", text: "tours.client_dashboard.urgent" },
      { target: "dashboard:findSpecialist", text: "tours.client_dashboard.findSpecialist" },
      { target: "dashboard:documents", text: "tours.client_dashboard.documents" },
      { target: "dashboard:subscriptions", text: "tours.client_dashboard.subscriptions" },
      { target: "dashboard:support", text: "tours.client_dashboard.support" },
      { target: "dashboard:requests", text: "tours.client_dashboard.requests" },
      { target: "header:support", text: "tours.common.support" },
    ],
    suggestions: ["suggest.client.plan", "suggest.client.lawyer", "suggest.client.document"],
  },
  {
    id: "client_subscription",
    match: ["/portal/client/subscription"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_subscription.title" },
      { target: "plans:current", text: "tours.client_subscription.current" },
      { target: "plans:period", text: "tours.client_subscription.period" },
      { target: "plan:lexgo-ai-pro", text: "tours.client_subscription.pro" },
      { target: "button:buy-plan:lexgo-ai-pro", text: "tours.client_subscription.buy" },
      { target: "plans:billing", text: "tours.client_subscription.billing" },
    ],
    suggestions: ["suggest.client.planCompare", "suggest.client.planPay"],
  },
  {
    id: "client_lawyers",
    match: ["/portal/client/lawyers"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_lawyers.title" },
      { target: "marketplace:ai-search", text: "tours.client_lawyers.search" },
      { target: "marketplace:lawyer-list", text: "tours.client_lawyers.list" },
      { target: "marketplace:filters", text: "tours.client_lawyers.filters" },
    ],
    suggestions: ["suggest.client.lawyer", "suggest.client.lawyerRating"],
  },
  {
    id: "client_services",
    match: ["/portal/client/services"],
    roles: ["client"],
    tour: [
      { target: "button:create-document", text: "tours.client_services.create" },
      { target: "documents:catalog-search", text: "tours.client_services.search" },
      { target: "documents:category-list", text: "tours.client_services.categories" },
      { target: "documents:direction-list", text: "tours.client_services.directions" },
      { target: "documents:template-list", text: "tours.client_services.templates" },
    ],
    suggestions: ["suggest.client.document", "suggest.client.documentCheck"],
  },
  {
    id: "client_documents",
    match: ["/portal/client/documents"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_documents.title" },
      { target: "documents:my-stats", text: "tours.client_documents.stats" },
      { target: "documents:my-filters", text: "tours.client_documents.filters" },
      { target: "documents:my-documents", text: "tours.client_documents.list" },
    ],
    suggestions: ["suggest.client.docDownload", "suggest.client.document"],
  },
  {
    id: "client_urgent",
    match: ["/portal/client/urgent"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_urgent.title" },
      { target: "urgent:terms", text: "tours.client_urgent.terms" },
      { target: "section:urgent-services", text: "tours.client_urgent.services" },
      { target: "urgent:video-consultation", text: "tours.client_urgent.video" },
      { target: "urgent:my-requests", text: "tours.client_urgent.mine" },
    ],
    suggestions: ["suggest.client.urgent", "suggest.client.urgentPrice"],
  },
  {
    id: "client_marketplace_orders",
    match: ["/portal/client/marketplace-orders"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_marketplace_orders.title" },
      { target: "orders:filters", text: "tours.client_marketplace_orders.filters" },
      { target: "client:marketplace-orders", text: "tours.client_marketplace_orders.list" },
    ],
    suggestions: ["suggest.client.orderStatus", "suggest.client.orderCancel"],
  },
  {
    id: "client_academy",
    match: ["/portal/client/academy"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_academy.title" },
      { target: "academy:categories", text: "tours.client_academy.categories" },
      { target: "academy:courses", text: "tours.client_academy.courses" },
    ],
    suggestions: ["suggest.client.academyStart", "suggest.client.academyFree"],
  },
  {
    id: "client_ai",
    match: ["/portal/client/ai"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_ai.title" },
      { target: "ai-chat:input", text: "tours.client_ai.input" },
      { target: "ai-chat:history", text: "tours.client_ai.history" },
    ],
    suggestions: ["suggest.client.aiLimit", "suggest.client.aiHistory"],
  },
  {
    id: "client_cases",
    match: ["/portal/client/cases"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_cases.title" },
      { target: "cases:list", text: "tours.client_cases.list" },
      { target: "order:status", text: "tours.client_cases.status" },
    ],
    suggestions: ["suggest.client.orderStatus", "suggest.client.refund"],
  },
  {
    id: "client_doc_analysis",
    match: ["/portal/client/doc-analysis"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_doc_analysis.title" },
      { target: "doc-analysis:text", text: "tours.client_doc_analysis.text" },
      { target: "doc-analysis:file", text: "tours.client_doc_analysis.file" },
      { target: "doc-analysis:options", text: "tours.client_doc_analysis.options" },
      { target: "button:doc-analysis-run", text: "tours.client_doc_analysis.run" },
    ],
    suggestions: ["suggest.client.documentCheck", "suggest.client.analysisPrice"],
  },
  {
    id: "client_gifts",
    match: ["/portal/client/gifts"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_gifts.title" },
      { target: "button:give-gift", text: "tours.client_gifts.give" },
      { target: "gifts:list", text: "tours.client_gifts.list" },
    ],
    suggestions: ["suggest.client.giftSend", "suggest.client.giftLink"],
  },
  {
    id: "client_intake",
    match: ["/portal/client/intake"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_intake.title" },
      { target: "intake:input", text: "tours.client_intake.input" },
      { target: "button:intake-analyze", text: "tours.client_intake.analyze" },
      { target: "intake:sources", text: "tours.client_intake.sources" },
    ],
    suggestions: ["suggest.client.intakeHow", "suggest.client.lawyer"],
  },
  {
    id: "client_lawyer_profile",
    match: ["/portal/client/lawyers/[id]"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_lawyer_profile.title" },
      { target: "marketplace:seller-summary", text: "tours.client_lawyer_profile.summary" },
      { target: "marketplace:seller-services", text: "tours.client_lawyer_profile.services" },
      { target: "marketplace:buy-box", text: "tours.client_lawyer_profile.buy" },
      { target: "marketplace:seller-reviews", text: "tours.client_lawyer_profile.reviews" },
    ],
    suggestions: ["suggest.client.buyService", "suggest.client.safeDeal"],
  },
  {
    id: "client_matches",
    match: ["/portal/client/matches"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_matches.title" },
      { target: "matches:list", text: "tours.client_matches.list" },
    ],
    suggestions: ["suggest.client.matchWhy", "suggest.client.lawyer"],
  },
  {
    id: "client_messages",
    match: ["/portal/client/messages"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_messages.title" },
      { target: "messages:inbox", text: "tours.client_messages.inbox" },
    ],
    suggestions: ["suggest.client.chatLawyer", "suggest.client.chatSafe"],
  },
  {
    id: "client_notifications",
    match: ["/portal/client/notifications"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_notifications.title" },
      { target: "notifications:filters", text: "tours.client_notifications.filters" },
      { target: "notifications:search", text: "tours.client_notifications.search" },
      { target: "notifications:list", text: "tours.client_notifications.list" },
    ],
    suggestions: ["suggest.client.notifRead", "suggest.client.notifSettings"],
  },
  {
    id: "client_packages",
    match: ["/portal/client/packages"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_packages.title" },
      { target: "packages:search", text: "tours.client_packages.search" },
      { target: "packages:tiers", text: "tours.client_packages.tiers" },
    ],
    suggestions: ["suggest.client.packagePick", "suggest.client.packageSave"],
  },
  {
    id: "client_payments",
    match: ["/portal/client/payments"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_payments.title" },
      { target: "payments:filters", text: "tours.client_payments.filters" },
      { target: "payments:history", text: "tours.client_payments.history" },
    ],
    suggestions: ["suggest.client.receipt", "suggest.client.operator"],
  },
  {
    id: "client_profile",
    match: ["/portal/client/profile"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_profile.title" },
      { target: "profile:personal", text: "tours.client_profile.personal" },
      { target: "profile:identity", text: "tours.client_profile.identity" },
      { target: "profile:two-factor", text: "tours.client_profile.twoFactor" },
      { target: "profile:telegram", text: "tours.client_profile.telegram" },
      { target: "profile:notification-prefs", text: "tours.client_profile.notifications" },
    ],
    suggestions: ["suggest.client.twoFactor", "suggest.client.telegramLink", "suggest.client.identity"],
  },
  {
    id: "client_referrals",
    match: ["/portal/client/referrals"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_referrals.title" },
      { target: "referrals:code", text: "tours.client_referrals.code" },
      { target: "referrals:share", text: "tours.client_referrals.share" },
      { target: "referrals:stats", text: "tours.client_referrals.stats" },
      { target: "referrals:invites", text: "tours.client_referrals.invites" },
    ],
    suggestions: ["suggest.client.referralShare", "suggest.client.referralBonus"],
  },
  {
    id: "client_reviews",
    match: ["/portal/client/reviews"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_reviews.title" },
      { target: "reviews:pending", text: "tours.client_reviews.pending" },
      { target: "reviews:mine", text: "tours.client_reviews.mine" },
    ],
    suggestions: ["suggest.client.reviewLeave", "suggest.client.unhappy"],
  },
  {
    id: "client_service_document",
    match: ["/portal/client/services/document/[serviceId]"],
    roles: ["client"],
    tour: [
      { target: "documents:fill-form", text: "tours.client_service_document.form" },
      { target: "documents:fill-preview", text: "tours.client_service_document.preview" },
      { target: "button:document-submit", text: "tours.client_service_document.submit" },
    ],
  },
  {
    id: "client_service_document_view",
    match: ["/portal/client/services/document/[serviceId]/view"],
    roles: ["client"],
    tour: [
      { target: "documents:template-preview", text: "tours.client_service_document_view.preview" },
      { target: "button:document-back", text: "tours.client_service_document_view.back" },
    ],
  },
  {
    id: "client_sos",
    match: ["/portal/client/sos"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_sos.title" },
      { target: "sos:call", text: "tours.client_sos.call" },
      { target: "sos:categories", text: "tours.client_sos.categories" },
      { target: "sos:description", text: "tours.client_sos.description" },
      { target: "button:sos-connect", text: "tours.client_sos.connect" },
    ],
    suggestions: ["suggest.client.urgent", "suggest.client.sosHow"],
  },
  {
    id: "client_warranty",
    match: ["/portal/client/warranty"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_warranty.title" },
      { target: "warranty:points", text: "tours.client_warranty.points" },
      { target: "warranty:form", text: "tours.client_warranty.form" },
      { target: "warranty:claims", text: "tours.client_warranty.claims" },
    ],
    suggestions: ["suggest.client.lawyerChange", "suggest.client.unhappy"],
  },
  {
    id: "client_works",
    match: ["/portal/client/works"],
    roles: ["client"],
    tour: [
      { target: "ai-help:current-page", text: "tours.client_works.title" },
      { target: "works:filters", text: "tours.client_works.filters" },
      { target: "works:list", text: "tours.client_works.list" },
    ],
    suggestions: ["suggest.client.workStatus", "suggest.client.docsWhere"],
  },
];
