import type { GuidePage } from "../types";

export const SELLER_PAGES: GuidePage[] = [
  {
    id: "seller_dashboard",
    match: ["/portal/lawyer", "/portal/advocate"],
    roles: ["lawyer", "advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.seller_dashboard.title" },
      { target: "seller-dashboard:stats", text: "tours.seller_dashboard.stats" },
      { target: "seller-dashboard:completeness", text: "tours.seller_dashboard.completeness" },
      { target: "seller-dashboard:tasks", text: "tours.seller_dashboard.tasks" },
      { target: "seller-dashboard:metrics", text: "tours.seller_dashboard.metrics" },
      { target: "seller-dashboard:new-orders", text: "tours.seller_dashboard.newOrders" },
    ],
    suggestions: ["suggest.seller.newOrder", "suggest.seller.verify", "suggest.seller.vacation"],
  },
  {
    id: "seller_opportunities",
    match: ["/portal/lawyer/marketplace", "/portal/advocate/opportunities"],
    roles: ["lawyer", "advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.seller_opportunities.title" },
      { target: "open-orders:list", text: "tours.seller_opportunities.list" },
    ],
    suggestions: ["suggest.seller.newOrder", "suggest.seller.orderTimer"],
  },
  {
    id: "seller_marketplace_orders",
    match: ["/portal/lawyer/marketplace-orders", "/portal/advocate/marketplace-orders"],
    roles: ["lawyer", "advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.seller_marketplace_orders.title" },
      { target: "orders:filters", text: "tours.seller_marketplace_orders.filters" },
      { target: "seller:marketplace-orders", text: "tours.seller_marketplace_orders.list" },
    ],
    suggestions: ["suggest.seller.completeOrder", "suggest.seller.payout", "suggest.seller.orders"],
  },
  {
    id: "seller_cases",
    match: ["/portal/lawyer/cases", "/portal/advocate/cases"],
    roles: ["lawyer", "advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.seller_cases.title" },
      { target: "cases:list", text: "tours.seller_cases.list" },
    ],
    suggestions: ["suggest.seller.caseStatus", "suggest.seller.caseAi"],
  },
  {
    id: "seller_urgent",
    match: ["/portal/lawyer/urgent", "/portal/advocate/urgent"],
    roles: ["lawyer", "advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.seller_urgent.title" },
      { target: "urgent-assigned:filters", text: "tours.seller_urgent.filters" },
      { target: "urgent-assigned:list", text: "tours.seller_urgent.list" },
    ],
    suggestions: ["suggest.seller.joinUrgent", "suggest.seller.urgentRequest"],
  },
  {
    id: "seller_tasks",
    match: ["/portal/lawyer/tasks", "/portal/advocate/tasks"],
    roles: ["lawyer", "advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.seller_tasks.title" },
      { target: "button:new-task", text: "tours.seller_tasks.add" },
      { target: "tasks:filters", text: "tours.seller_tasks.filters" },
      { target: "tasks:board", text: "tours.seller_tasks.board" },
    ],
    suggestions: ["suggest.seller.newTask", "suggest.seller.moveTask"],
  },
  {
    id: "seller_calendar",
    match: ["/portal/lawyer/calendar", "/portal/advocate/calendar"],
    roles: ["lawyer", "advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.seller_calendar.title" },
      { target: "button:add-event", text: "tours.seller_calendar.add" },
      { target: "button:deadline-calculator", text: "tours.seller_calendar.calc" },
      { target: "calendar:month", text: "tours.seller_calendar.month" },
      { target: "calendar:agenda", text: "tours.seller_calendar.agenda" },
    ],
    suggestions: ["suggest.seller.hearing", "suggest.seller.deadline"],
  },
  {
    id: "seller_clients",
    match: ["/portal/lawyer/clients", "/portal/advocate/clients"],
    roles: ["lawyer", "advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.seller_clients.title" },
      { target: "button:add-client", text: "tours.seller_clients.add" },
      { target: "button:conflict-check", text: "tours.seller_clients.conflict" },
      { target: "seller:client-list", text: "tours.seller_clients.list" },
    ],
    suggestions: ["suggest.seller.addClient", "suggest.seller.conflict"],
  },
  {
    id: "lawyer_services",
    match: ["/portal/lawyer/services"],
    roles: ["lawyer"],
    tour: [
      { target: "ai-help:current-page", text: "tours.lawyer_services.title" },
      { target: "services:catalog", text: "tours.lawyer_services.catalog" },
      { target: "services:policy", text: "tours.lawyer_services.policy" },
      { target: "button:save-services", text: "tours.lawyer_services.save" },
    ],
    suggestions: ["suggest.seller.prices", "suggest.seller.addService"],
  },
  {
    id: "lawyer_documents",
    match: ["/portal/lawyer/documents"],
    roles: ["lawyer"],
    tour: [
      { target: "ai-help:current-page", text: "tours.lawyer_documents.title" },
      { target: "doc-templates:list", text: "tours.lawyer_documents.list" },
    ],
    suggestions: ["suggest.seller.templates"],
  },
  {
    id: "seller_document_requests",
    match: ["/portal/lawyer/document-requests", "/portal/advocate/document-requests"],
    roles: ["lawyer", "advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.seller_document_requests.title" },
      { target: "document-requests:tabs", text: "tours.seller_document_requests.tabs" },
      { target: "document-requests:filters", text: "tours.seller_document_requests.filters" },
      { target: "list:document-requests", text: "tours.seller_document_requests.list" },
    ],
    suggestions: ["suggest.seller.claimRequest", "suggest.seller.sendDocument", "suggest.seller.works"],
  },
  {
    id: "seller_document_editor",
    match: ["/portal/lawyer/document-requests/[recordId]/editor", "/portal/advocate/document-requests/[recordId]/editor"],
    roles: ["lawyer", "advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.seller_document_editor.title" },
      { target: "doc-editor:document", text: "tours.seller_document_editor.document" },
      { target: "button:editor-source", text: "tours.seller_document_editor.source" },
      { target: "button:editor-finalize", text: "tours.seller_document_editor.finalize" },
      { target: "doc-editor:request", text: "tours.seller_document_editor.request" },
      { target: "doc-editor:side-panel", text: "tours.seller_document_editor.side" },
    ],
  },
  {
    id: "seller_files",
    match: ["/portal/lawyer/files", "/portal/advocate/files"],
    roles: ["lawyer", "advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.seller_files.title" },
      { target: "button:upload-file", text: "tours.seller_files.upload" },
      { target: "button:new-folder", text: "tours.seller_files.folder" },
      { target: "files:sections", text: "tours.seller_files.sections" },
      { target: "files:list", text: "tours.seller_files.list" },
    ],
    suggestions: ["suggest.seller.uploadFile", "suggest.seller.newFolder"],
  },
  {
    id: "seller_messages",
    match: ["/portal/lawyer/chat", "/portal/advocate/messages"],
    roles: ["lawyer", "advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.seller_messages.title" },
      { target: "messages:inbox", text: "tours.seller_messages.inbox" },
    ],
    suggestions: ["suggest.seller.chatFile", "suggest.seller.newMessages"],
  },
  {
    id: "seller_meetings",
    match: ["/portal/lawyer/meetings", "/portal/advocate/meetings"],
    roles: ["lawyer", "advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.seller_meetings.title" },
      { target: "meetings:create", text: "tours.seller_meetings.create" },
      { target: "meetings:today", text: "tours.seller_meetings.today" },
      { target: "seller:meeting-list", text: "tours.seller_meetings.list" },
    ],
    suggestions: ["suggest.seller.startMeeting", "suggest.seller.pastMeetings"],
  },
  {
    id: "seller_notifications",
    match: ["/portal/lawyer/notifications", "/portal/advocate/notifications"],
    roles: ["lawyer", "advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.seller_notifications.title" },
      { target: "notifications:filters", text: "tours.seller_notifications.filters" },
      { target: "notifications:search", text: "tours.seller_notifications.search" },
      { target: "notifications:list", text: "tours.seller_notifications.list" },
    ],
    suggestions: ["suggest.seller.notifySettings", "suggest.seller.readAll"],
  },
  {
    id: "lawyer_ai",
    match: ["/portal/lawyer/ai"],
    roles: ["lawyer"],
    tour: [
      { target: "ai-help:current-page", text: "tours.lawyer_ai.title" },
      { target: "ai-chat:input", text: "tours.lawyer_ai.input" },
      { target: "ai-chat:history", text: "tours.lawyer_ai.history" },
    ],
    suggestions: ["suggest.seller.aiAsk", "suggest.seller.aiLimit"],
  },
  {
    id: "seller_assistant",
    match: ["/portal/lawyer/assistant", "/portal/advocate/assistant"],
    roles: ["lawyer", "advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.seller_assistant.title" },
      { target: "assistant:case-input", text: "tours.seller_assistant.input" },
      { target: "assistant:tools", text: "tours.seller_assistant.tools" },
      { target: "button:assistant-run", text: "tours.seller_assistant.run" },
    ],
    suggestions: ["suggest.seller.chronology", "suggest.seller.missingDocs"],
  },
  {
    id: "seller_profile",
    match: ["/portal/lawyer/profile", "/portal/advocate/profile"],
    roles: ["lawyer", "advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.seller_profile.title" },
      { target: "profile:visibility", text: "tours.seller_profile.visibility" },
      { target: "seller:profile-edit", text: "tours.seller_profile.personal" },
      { target: "profile:practice-areas", text: "tours.seller_profile.areas" },
      { target: "profile:pricing", text: "tours.seller_profile.pricing" },
      { target: "profile:two-factor", text: "tours.seller_profile.security" },
    ],
    suggestions: ["suggest.seller.profile", "suggest.seller.verify", "suggest.seller.prices"],
  },
  {
    id: "seller_referrals",
    match: ["/portal/lawyer/referrals", "/portal/advocate/referrals"],
    roles: ["lawyer", "advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.seller_referrals.title" },
      { target: "referrals:code", text: "tours.seller_referrals.code" },
      { target: "referrals:share", text: "tours.seller_referrals.share" },
      { target: "referrals:stats", text: "tours.seller_referrals.stats" },
      { target: "referrals:invites", text: "tours.seller_referrals.invites" },
    ],
    suggestions: ["suggest.seller.referral", "suggest.seller.referralReward"],
  },
  {
    id: "seller_promotion",
    match: ["/portal/lawyer/promotion", "/portal/advocate/promotion"],
    roles: ["lawyer", "advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.seller_promotion.title" },
      { target: "promotion:analytics", text: "tours.seller_promotion.analytics" },
      { target: "promotion:packages", text: "tours.seller_promotion.packages" },
    ],
    suggestions: ["suggest.seller.promotion", "suggest.seller.promotionStats"],
  },
  {
    id: "seller_subscription",
    match: ["/portal/lawyer/subscription", "/portal/advocate/subscription"],
    roles: ["lawyer", "advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.seller_subscription.title" },
      { target: "plans:current", text: "tours.seller_subscription.current" },
      { target: "plans:period", text: "tours.seller_subscription.period" },
      { target: "plan:lexgo-ai-pro", text: "tours.seller_subscription.pro" },
      { target: "button:buy-plan:lexgo-ai-pro", text: "tours.seller_subscription.buy" },
    ],
    suggestions: ["suggest.seller.plan", "suggest.seller.planDiscount"],
  },
  {
    id: "advocate_organization",
    match: ["/portal/advocate/organization"],
    roles: ["advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.advocate_organization.title" },
      { target: "button:create-organization", text: "tours.advocate_organization.create" },
      { target: "organization:list", text: "tours.advocate_organization.list" },
    ],
    suggestions: ["suggest.seller.orgCreate", "suggest.seller.orgMember"],
  },
  {
    id: "advocate_organization_dashboard",
    match: ["/portal/advocate/organization/[orgId]"],
    roles: ["advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.advocate_organization_dashboard.title" },
      { target: "button:org-workload", text: "tours.advocate_organization_dashboard.workload" },
      { target: "organization:summary", text: "tours.advocate_organization_dashboard.summary" },
      { target: "organization:members", text: "tours.advocate_organization_dashboard.members" },
      { target: "organization:active-orders", text: "tours.advocate_organization_dashboard.active" },
    ],
    suggestions: ["suggest.seller.orgWorkload", "suggest.seller.orgMember"],
  },
  {
    id: "advocate_organization_workload",
    match: ["/portal/advocate/organization/[orgId]/workload"],
    roles: ["advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.advocate_organization_workload.title" },
      { target: "organization:workload-filter", text: "tours.advocate_organization_workload.filter" },
      { target: "organization:workload-list", text: "tours.advocate_organization_workload.list" },
    ],
    suggestions: ["suggest.seller.orgFilter"],
  },
  {
    id: "seller_chat_room",
    match: ["/portal/chat/[roomId]"],
    roles: ["lawyer", "advocate"],
    tour: [
      { target: "ai-help:current-page", text: "tours.seller_chat_room.title" },
      { target: "chat-room:messages", text: "tours.seller_chat_room.messages" },
      { target: "chat-room:composer", text: "tours.seller_chat_room.composer" },
    ],
  },
];
